apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: default
spec:
  interval: 1m # 1h
  chart:
    spec:
      chart: keycloak
      version: "24.7.4"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  targetNamespace: default
  values:
    postgresql:
      enabled: false
    externalDatabase:
      host: pmh-postgres.default.svc.cluster.local
      port: 5432
      database: postgres
      user: user
      password: "SuperSecretPassword46f"
  timeout: 10m
