apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sso-helper
  namespace: default
spec:
  imageRepositoryRef:
    name: sso-helper
  policy:
    filterTags:
      pattern: '^[a-f0-9]{7,40}$'
