apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sso-helper
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sso-helper
  policy:
    semver:
      range: ">=0.0.0"
