apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pmh-postgres
  namespace: default

  labels:
    app: pmh-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi