apiVersion: v1
kind: Secret
metadata:
  name: pmh-postgres-secrets
  namespace: default

type: Opaque
data:
  # echo "password" | base64
  root_password: U3VwZXJTZWNyZXRQYXNzd29yZDQ2Zg==
  db_user: cG9zdGdyZXM= # echo "postgres" | base64
