apiVersion: v1
kind: Service
metadata:
  name: pmh-postgres
  namespace: default

  labels:
    app: pmh-app
spec:
  ports:
    - port: 5432
  type: LoadBalancer
  selector:
    app: pmh-app
    tier: postgres